name: Deploy on GitHub page

on:
  push:
    branches: ['main']

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: package.json
      - uses: actions/configure-pages@v2
        with:
          static_site_generator: next
      - uses: actions/cache@v3
        with:
          path: |
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
      - name: Install dependencies
        run: yarn --immutable
      - name: Build with Next.js
        run: yarn next build
      - name: Static HTML export with Next.js
        run: yarn next export
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./out
      - uses: actions/deploy-pages@v1
        id: deployment
